-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('MENUNGGU_PEMBAYARAN', 'MENUNGGU_KONFIRMASI', 'DIPROSES', 'SIAP_DIANTAR', 'DALAM_PERJALANAN', 'SELESAI', 'DIBATALKAN') NOT NULL DEFAULT 'MENUNGGU_PEMBAYARAN';
